/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package splash.screen;

/**
 *
 * @author SSJ Shreyas
 */
public class AboutUs extends javax.swing.JFrame {

    /**
     * Creates new form AboutUs
     */
    public AboutUs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Viewport = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        scroll = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Viewport.setOpaque(false);
        Viewport.setLayout(null);

        scroll.setEditable(false);
        scroll.setColumns(20);
        scroll.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        scroll.setRows(5);
        scroll.setText("Bethesda Game Studios® is the award-winning development team known around \nthe world for their groundbreaking work on the The Elder Scrolls and Fallout\nseries. Creators of the 2006 ‘Game of the Year’, The Elder Scrolls IV: \nOblivion®, the 2008 ‘Game of the Year’, Fallout® 3, the 2011 ‘Game of the \nYear’, The Elder Scrolls V: Skyrim®, and most recently, the 2015 ‘Game of \nthe Year’, the record-breaking Fallout® 4. Bethesda Game Studios has earned \nits reputation as one of the industry’s most respected and accomplished game\ndevelopment studios.");
        scroll.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        scroll.setOpaque(false);
        jScrollPane2.setViewportView(scroll);

        Viewport.add(jScrollPane2);
        jScrollPane2.setBounds(0, 210, 620, 150);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splash/screen/BethesdaFrontDesk.jpg"))); // NOI18N
        Viewport.add(jLabel1);
        jLabel1.setBounds(10, 0, 610, 210);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Viewport, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Viewport, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutUs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Viewport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea scroll;
    // End of variables declaration//GEN-END:variables
}
