/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package splash.screen;

/**
 *
 * @author SSJ Shreyas
 */
public class CompanyInfo extends javax.swing.JFrame {

    /**
     * Creates new form ComapanyInfo
     */
    public CompanyInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cdt = new javax.swing.JButton();
        pro = new javax.swing.JButton();
        wh = new javax.swing.JButton();
        ld = new javax.swing.JButton();
        bonus = new javax.swing.JButton();
        salary = new javax.swing.JButton();
        emp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        cdt.setText("Company Departments");
        cdt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cdtMouseClicked(evt);
            }
        });
        getContentPane().add(cdt);
        cdt.setBounds(31, 94, 170, 23);

        pro.setText("Project");
        pro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proMouseClicked(evt);
            }
        });
        pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proActionPerformed(evt);
            }
        });
        getContentPane().add(pro);
        pro.setBounds(31, 135, 90, 23);

        wh.setText("Working Hours");
        wh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                whMouseClicked(evt);
            }
        });
        getContentPane().add(wh);
        wh.setBounds(31, 176, 130, 23);

        ld.setText("Leave Details");
        ld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ldMouseClicked(evt);
            }
        });
        getContentPane().add(ld);
        ld.setBounds(31, 217, 130, 23);

        bonus.setText("Bonus");
        bonus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bonusMouseClicked(evt);
            }
        });
        getContentPane().add(bonus);
        bonus.setBounds(265, 51, 90, 23);

        salary.setText("Salary");
        salary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salaryMouseClicked(evt);
            }
        });
        salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryActionPerformed(evt);
            }
        });
        getContentPane().add(salary);
        salary.setBounds(265, 94, 90, 23);

        emp.setText("Employee");
        emp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empMouseClicked(evt);
            }
        });
        getContentPane().add(emp);
        emp.setBounds(31, 51, 110, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splash/screen/bk4.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        setSize(new java.awt.Dimension(416, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proActionPerformed

    private void salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryActionPerformed

    private void empMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empMouseClicked
        Employee main=new Employee();
         main.setVisible(true);
    }//GEN-LAST:event_empMouseClicked

    private void cdtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cdtMouseClicked
        Company_Dept main=new Company_Dept();
         main.setVisible(true);
    }//GEN-LAST:event_cdtMouseClicked

    private void proMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proMouseClicked
        project main=new project();
         main.setVisible(true);
    }//GEN-LAST:event_proMouseClicked

    private void whMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_whMouseClicked
        workinghours main=new workinghours();
         main.setVisible(true);
    }//GEN-LAST:event_whMouseClicked

    private void ldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ldMouseClicked
        Leave main=new Leave();
         main.setVisible(true);
    }//GEN-LAST:event_ldMouseClicked

    private void bonusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bonusMouseClicked
        bonus main=new bonus();
         main.setVisible(true);
    }//GEN-LAST:event_bonusMouseClicked

    private void salaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salaryMouseClicked
        salary main=new salary();
         main.setVisible(true);
    }//GEN-LAST:event_salaryMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompanyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompanyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompanyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompanyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompanyInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bonus;
    private javax.swing.JButton cdt;
    private javax.swing.JButton emp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton ld;
    private javax.swing.JButton pro;
    private javax.swing.JButton salary;
    private javax.swing.JButton wh;
    // End of variables declaration//GEN-END:variables
}
